name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify cluster connectivity
        run: kubectl get nodes

      - name: Deploy to Kubernetes
        run: kubectl apply -f nginx-deployment.yaml

      - name: Wait for Deployment rollout
        run: kubectl rollout status deployment/nginx-deployment --timeout=120s

      - name: Verify Pods
        run: kubectl get pods -o wide

