name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG_DATA" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify cluster connectivity
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy manifests
        run: kubectl apply -f nginx-deployment.yaml

      - name: Wait for Deployment rollout
        run: kubectl rollout status deployment/nginx-deployment --timeout=120s

      - name: Verify Pods
        run: kubectl get pods -o wide

